![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [32]:
import numpy as np

In [33]:
my_array=np.arange(0,10)
my_array_inverso=my_array[-1:0:-1]
print(my_array_inverso)
my_array_impares=my_array_inverso[my_array_inverso%2!=0]
print(my_array_impares)


[9 8 7 6 5 4 3 2 1]
[9 7 5 3 1]


In [34]:
my_array_impares_directo=my_array[-1:0:-1][my_array[-1:0:-1]%2!=0]
print(my_array_impares_directo)

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [35]:
my_array_87=my_array[8:6:-1]
print(my_array_87)

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [36]:
my_array_210=my_array[2::-1]
print(my_array_210)

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [37]:
vector4=np.arange(1,21)
matriz4=vector4.reshape(4,5)
print(matriz4)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [38]:

matriz5=matriz4[0:2,0:2]
print(matriz5)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [39]:
# Filas: de la 0 a la 3 sin incluir con saltos de 2, osea la 0 y la 2
# Columnas: de 0 al 5 índice sin incluir con saltos de 2, osea el 0,2,4

matriz6=matriz4[0:3:2,0:5:2]
print(matriz6)

[[ 1  3  5]
 [11 13 15]]


In [40]:
# para que no cambie el valor. solo actua a nivel de celda
np.random.seed(123)
np.random.randint(0,10,(10,10))

array([[2, 2, 6, 1, 3, 9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3, 4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7, 2, 4, 8, 0, 7],
       [9, 3, 4, 6, 1, 5, 6, 2, 1, 8],
       [3, 5, 0, 2, 6, 2, 4, 4, 6, 3],
       [0, 6, 4, 7, 6, 7, 1, 5, 7, 9],
       [2, 4, 8, 1, 2, 1, 1, 3, 5, 9],
       [0, 8, 1, 6, 3, 3, 5, 9, 7, 9],
       [2, 3, 3, 3, 8, 6, 9, 7, 6, 3],
       [9, 6, 6, 6, 1, 3, 4, 3, 1, 0]], dtype=int32)

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [41]:

matriz7=matriz4[0:3:1,4::-1]
print(matriz7)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [42]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x8=x[x=="Loro"]
print(x8)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [43]:
x9=np.arange(20).reshape(2,5,2)
print(x9)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [44]:
print(matriz4, "\n")
matriz10=matriz4[::-1,::-1]
print(matriz10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [45]:
zeros=np.zeros(10, dtype=int)
zeros[4]=1
print(zeros)

[0 0 0 0 1 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [46]:
vector12=np.arange(49,9,-1)
print(vector12)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [47]:
#devuelve los valores
vector13=np.array([1,2,0,0,4,0])
vector13_2=vector13[vector13!=0]
print(vector13_2)
#devuelve los indices

[1 2 4]


In [48]:
# np.where se comporta distinto según cuántos argumentos le pases:
# Con 1 argumento (solo la condición), devuelve los INDICES donde la condición es verdadera. 
# Con 3 argumentos (condición, si_verdadero_ponesto, si_falso_ponesto), devuelve un array nuevo con los VALORES, eligiendo elemento a elemento:

vector13=np.array([1,2,0,0,4,0])
no_cero = np.where(vector13 != 0)[0]
print(no_cero)

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [49]:
matriz14=np.random.randint(0, 10, size=(10,10))
print(matriz14)


[[5 8 6 8 9 1 0 3 1 3]
 [4 7 6 1 4 3 3 7 6 8]
 [6 4 4 7 0 0 9 8 8 4]
 [8 6 1 6 8 7 9 1 7 1]
 [7 9 8 7 1 3 1 8 7 5]
 [1 2 5 2 2 9 3 2 6 7]
 [9 1 3 8 3 7 9 9 3 3]
 [5 6 0 8 7 7 4 4 5 0]
 [8 9 2 5 1 5 9 2 4 3]
 [0 3 7 7 2 5 1 7 5 9]]


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [50]:
vector15=np.random.randint(10, size=30)
print(vector15.mean())

4.766666666666667


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [51]:

matriz16 = np.ones((5, 5), dtype=int)
matriz16[1:-1, 1:-1] = 0
print(matriz16)  # modifica la matriz!! si no quiero, hacer copia!!

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [52]:
matriz17=np.zeros((8,8), dtype=int)
matriz17[0::1,0::2]=1
print(matriz17, "\n")

matriz17_2=np.ones((8,8), dtype=int)
matriz17_2[0::1,0::2]=0
print(matriz17_2)


[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]] 

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [53]:
matriz17_3=np.zeros((8,8), dtype=int)
matriz17_3[::2, 1::2] = 1   # cambio por unos las filas pares (0, 2, 4, 6), columnas impares (1, 3, 5, 7)
matriz17_3[1::2, ::2] = 1   # cambio por unos las filas impares (1, 3, 5, 7), columnas pares (0, 2, 4, 6)

print(matriz17_3)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [54]:
A=np.array([0,1,0,1,0,1,0,1])
np.tile(A, 8).reshape(8,8)


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [55]:
# otra manera con tile, como realmente pide, es detectar el patron que quiero repetir, 
# en este caso una matrix 2x2

B=np.array([[1,0],
           [0,1]])

np.tile(B, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [56]:
matriz9=np.random.rand(5,5)
norma=(matriz9-np.mean(matriz9))/np.std(matriz9)
print(matriz9) #valores entre 0 y 1
print(np.mean(matriz9)) #valores entre 0 y 1
print(np.std(matriz9)) 
print(norma)

[[0.90987166 0.1286312  0.08178009 0.13841557 0.39937871]
 [0.42430686 0.56221838 0.12224355 0.2013995  0.81164435]
 [0.46798757 0.80793821 0.00742638 0.55159273 0.93193215]
 [0.58217546 0.20609573 0.71775756 0.37898585 0.66838395]
 [0.02931972 0.63590036 0.03219793 0.74478066 0.472913  ]]
0.44061108490976664
0.29002402182029685
[[ 1.61800589 -1.07570361 -1.23724578 -1.04196718 -0.14216883]
 [-0.0562168   0.41930076 -1.09772816 -0.82479921  1.27931908]
 [ 0.09439387  1.26654034 -1.49361664  0.38266362  1.69407024]
 [ 0.48811258 -0.80860667  0.95559835 -0.21248321  0.78535861]
 [-1.41812861  0.67335551 -1.40820456  1.04877371  0.1113767 ]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [57]:
sec10=np.arange(11)
print(sec10)
y=sec10.copy()
z=sec10.copy()
# Importante: precedencia de operadores: en Python & se evalúa antes que >= y <=, 
# por lo que necesito poner parentesis para que calcule las comparaciones antes y no de error
y[(y >= 3) & (y <= 8)]=-1
print(y)

# *= quiere decir ese mismo valor por -1
z[(z >= 3) & (z<= 8)] *= -1
print(z)

# Si negar es eliminarlo:
k=y[y!=-1].copy()
print(k)



[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
[ 0  1  2  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [ ]:
tablero= np.full((10, 10), " ")
barco1 = [(0, 1), (1, 1)]
barco2 = [(1, 3), (1, 4), (1, 5), (1, 6)]
posiciones_a_cambiar=barco1+barco2


for fila, columna in posiciones_a_cambiar:
    tablero[fila, columna] = "o"
# tablero[1,4]="X"
# tablero[5,5]="-"
print(tablero, "\n")

# Bucle para crear un posible barco nuevo a posicionar Y POSICIONARLO (solo break cuando lo consigue salir)
while True:
    #Creamos var booleana aleatoria: True=horizontal; False=vertical
    longitud_barco=4
    casillas=[]
    horizontal=np.random.rand()<0.5
    if horizontal==True:
        # Creamos una fila aleatoria. Imagina 3
        fila=np.random.randint(0,10)
        #Creamos una col aleatoria. Imagina 8: NOOO, fuerza a que sea de 0 al 7 NO ICLUIDO
        col=np.random.randint(0,7)
        for i in range(longitud_barco):
            casillas.append([fila, col+i])
    else: #Booleano False (orientacion vertical)
        # Creamos una fila aleatoria. Imagina 8: NOOO, fuerza a que sea de 0 a 7 NO ICLUIDO
        col=np.random.randint(0,10)
        # Creamos una col aleatoria.
        fila=np.random.randint(0,7)
        for i in range(longitud_barco):
            casillas.append([fila+i, col])

    # El barco que he creado cabe? Reviso cada una de las posiciones
    # Si cabe en todas las posiciones, libre=True y que lo meta y al terminar salga del bucle, 
    # si no cabe: libre= false, no llega a añadir nada y VUELVE A INTENTAR EL BUCLE WHILE
    # solo sale de while si se llegan a poner las 4casillas
    libre=True
    for j,k in casillas:
        if tablero[j,k]=="o" or tablero[j,k]=="X":
         libre=False
         print("Encontre una posición que no cabe, volvamos a empezar")
         break

    if libre: #true para todas las posiciones de casillas
        for fila, columna in casillas:
            tablero[fila, columna] = "o"
        break

print(tablero)

#Ahora vamos colocar o en casillas y EVITAR SOLAPAMIENTOS
#Hay que comprobar que las 4 posiciones estan libres, y sino volver a sortear



[[' ' 'o' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'o' ' ' 'o' 'o' 'o' 'o' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']] 

[[' ' 'o' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'o' ' ' 'o' 'o' 'o' 'o' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' 'o' 'o' 'o' 'o']]
